Document: scaleimp
Title: Debian scaleimp Manual
Author: <insert document author here>
Abstract: This manual describes what scaleimp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/scaleimp/scaleimp.sgml.gz

Format: postscript
Files: /usr/share/doc/scaleimp/scaleimp.ps.gz

Format: text
Files: /usr/share/doc/scaleimp/scaleimp.text.gz

Format: HTML
Index: /usr/share/doc/scaleimp/html/index.html
Files: /usr/share/doc/scaleimp/html/*.html
