name: build

on:
  push:
    paths:
      - '*'
    pull_request:
      paths:
        - '*'

jobs:
  build_debian:
    runs-on: debian-11
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        - run: |
          sudo apt-get install -y --no-install-recommends tk dpkg-dev debhelper

        - name: Perform build
          run: |
            dpkg-buildpackage -b
        - uses: actions/upload-artifact@v3
          with:
            name: debian-package
            path: ../scaleimp_1.0.0-1_all.deb
            
#fedora 35
#    Dependencies
#        rpmbuild tk
#    Checkout
#        git clone https://github.com/Montandalar/ScaleImpTcl
#    Build
#        mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
#        cd ScaleImpTcl
#        cp fedora/scaleimp.spec ~/rpmbuild/SPECS/
#        rpmbuild -bs ~/rpmbuild/SPECS/scaleimp.spec
#        rpmbuild -ba ~/rpmbuild/SPECS/scaleimp.spec
#    upload artifact:
#        ~/rpmbuild/RPMS/noarch/scaleimp-${ver}.rpm
#
